const carActionsTypes ={
    FETCH_CARS_REQUEST:'FETCH_CARS_REQUEST',
    FETCH_CARS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_CARS_FAILURE: 'FETCH_CARS_FAILURE',
    UPDATE_CAR: 'UPDATE_CAR',
    DELETE_CAR: 'DELETE_CAR',
    CREATE_CAR: 'CREATE_CAR'
}

export {carActionsTypes}